#!/bin/sh

start() {
	printf "Starting Storage: "
	/sbin/init-storage.sh \
		&& echo "OK" || echo "FAIL"
}

stop() {
	:
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
