#!/bin/sh

start() {
	printf "Starting USB gadget: "
	start-stop-daemon --start --background --oknodo --quiet --exec \
	/sbin/path-exist-poller 2 /sys/bus/gadget/drivers/configfs-gadget.g1 /sbin/usb-gadget.sh \
		&& echo "OK" || echo "FAIL"
}

stop() {
	:
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
